import { NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';

export async function GET() {
  const swCode = `/* eslint-disable no-undef */
// ===========================================
// SERVICE WORKER DYNAMICALLY GENERATED BY NEXT.JS
// ===========================================
const SW_VERSION = "2026-07-20-fcm";
console.log("[SW] Initializing FCM Service Worker version " + SW_VERSION);

importScripts("https://www.gstatic.com/firebasejs/10.12.0/firebase-app-compat.js");
importScripts("https://www.gstatic.com/firebasejs/10.12.0/firebase-messaging-compat.js");

const firebaseConfig = {
  apiKey: "${process.env.NEXT_PUBLIC_FIREBASE_API_KEY || ''}",
  authDomain: "${process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN || ''}",
  projectId: "${process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID || ''}",
  storageBucket: "${process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET || ''}",
  messagingSenderId: "${process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID || ''}",
  appId: "${process.env.NEXT_PUBLIC_FIREBASE_APP_ID || ''}"
};

try {
  firebase.initializeApp(firebaseConfig);
  const messaging = firebase.messaging();

  messaging.onBackgroundMessage((payload) => {
    console.log("[FCM SW] Background message received:", payload);
    const data = payload.data || {};
    const notificationTitle = data.title || payload.notification?.title || "Transavic ERP";
    const isSilent = data.silent === "true";

    const notificationOptions = {
      body: data.body || payload.notification?.body || "Tienes una nueva alerta en el ERP.",
      icon: "/icon-192.png",
      badge: "/icon-192.png",
      requireInteraction: !isSilent,
      data: data,
      tag: data.tag || "transavic-alert",
      renotify: !isSilent && data.renotify === "true",
      silent: isSilent,
    };

    return self.registration.showNotification(notificationTitle, notificationOptions);
  });
} catch (error) {
  console.error("[FCM SW] Error initializing Firebase SW:", error);
}

// Skip waiting and claim clients
self.addEventListener('install', () => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

// Click behavior to open/focus PWA window
self.addEventListener('notificationclick', function(event) {
  event.notification.close();
  const raw = event.notification.data || {};
  const data = (raw.FCM_MSG && raw.FCM_MSG.data) ? raw.FCM_MSG.data : raw;

  // Priority redirect url
  let targetUrl = '/dashboard';
  if (typeof data.url === 'string' && data.url.startsWith('/')) {
    targetUrl = data.url;
  }

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then(function(windowClients) {
      // Reuse open tab
      for (var i = 0; i < windowClients.length; i++) {
        var client = windowClients[i];
        if ('focus' in client) {
          if ('navigate' in client) {
            return client.navigate(targetUrl)
              .then(function(c) { return (c || client).focus(); })
              .catch(function() { return clients.openWindow(targetUrl); });
          }
          return client.focus();
        }
      }
      // Open new tab if none open
      if (clients.openWindow) {
        return clients.openWindow(targetUrl);
      }
    })
  );
});
`;

  return new NextResponse(swCode, {
    headers: {
      'Content-Type': 'application/javascript',
      'Cache-Control': 'no-store, no-cache, must-revalidate, proxy-revalidate',
    },
  });
}
