// src/app/api/version/route.ts
import { NextResponse } from "next/server";
import fs from "fs";
import path from "path";

// Read the BUILD_ID generated by Next.js at build time.
// Each Vercel deployment generates a unique BUILD_ID.
function getBuildId(): string {
  try {
    const buildIdPath = path.join(process.cwd(), ".next", "BUILD_ID");
    return fs.readFileSync(buildIdPath, "utf-8").trim();
  } catch {
    // Fallback: use a timestamp-based ID (changes on each server restart)
    return Date.now().toString();
  }
}

export async function GET() {
  return NextResponse.json(
    { buildId: getBuildId() },
    {
      headers: {
        "Cache-Control": "no-store, no-cache, must-revalidate",
        Pragma: "no-cache",
      },
    },
  );
}
