// src/app/api/version/route.ts
import { NextResponse } from "next/server";
import fs from "fs";
import path from "path";

let fallbackBuildId: string | null = null;

// Read the BUILD_ID generated by Next.js at build time.
// Each Vercel deployment generates a unique BUILD_ID.
function getBuildId(): string {
  if (process.env.NODE_ENV === "development") {
    return "development";
  }

  try {
    const buildIdPath = path.join(process.cwd(), ".next", "BUILD_ID");
    return fs.readFileSync(buildIdPath, "utf-8").trim();
  } catch {
    // Fallback: use a persistent timestamp for the lifetime of the server process
    if (!fallbackBuildId) {
      fallbackBuildId = Date.now().toString();
    }
    return fallbackBuildId;
  }
}

export async function GET() {
  return NextResponse.json(
    { buildId: getBuildId() },
    {
      headers: {
        "Cache-Control": "no-store, no-cache, must-revalidate",
        Pragma: "no-cache",
      },
    },
  );
}
